# Generated by Django 4.2.6 on 2023-10-11 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('RatingID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('RequestID', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('RatingValue', models.IntegerField()),
                ('Comments', models.TextField()),
                ('Client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_ratings', to='Account.user')),
                ('Worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_ratings', to='Account.user')),
            ],
        ),
    ]
